### ISSUE TITLE
SNK 40th: which emulator for psychos.zip?

### ISSUE THREAD

**Issue by lioneltrs** [shawngmc/game-extraction-toolbox#53]
Could you please tell which emulator can run psychos.zip (and psychosj.zip) from the SNK 40th Anniversary Collection?
I tried Retroarch mame2000, mame2003, mame2003plus, fbneo, fbalpha2012 without success.
Thanks for software an keep up the good work,
Lioneltrs

**Comment by lioneltrs** [comment]
I think that I found the answer: mame_libretro works with psychos.zip

**Comment by Feilakas** [comment]
> I think that I found the answer: mame_libretro works with psychos.zip
The current script cannot find the two files horizon."x" and vertical."y" in any of the included games and instead creates "blank" placeholder files (I forget if they're filled with 0000 or FFFF) of the same size as shims.

FBNeo performs a CRC check and since these two fail, if refuses to run the ROMs.
I do believe that there is a method to "tell" it to run the modified ROMs which involves putting the files in a special "override" folder or something like that.

Like you said, the "current" MAME (which is what mame_libretro basically is) will run ROMs that contain all the files even if the CRC-check fails.

**Comment by lioneltrs** [comment]
Thank you!

**Comment by lioneltrs** [comment]
Thank you!
